#!/usr/bin/env groovy

node ('master') {
    def rtServer
    def buildInfo
    def dockerReg="jfrog.local:5001"
    def dockerNamespace='jbaruch'
    def dockerFinalTag="${env.BUILD_NUMBER}"
    def tagDockerApp
    def rtDocker
    stage('initializing') {
      rtServer = Artifactory.newServer url: "http://jfrog.local/artifactory", credentialsId: CREDENTIALS
      withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: CREDENTIALS, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
        rtDocker = Artifactory.docker("${env.USERNAME}", "${env.PASSWORD}")
      }
      git url: 'https://github.com/jbaruch/spring-boot-docker.git'
    }
    buildInfo.env.capture = true
    stage('maven build') {
      dir ('examples-java') {
        def rtMaven = Artifactory.newMavenBuild()
        rtMaven.resolver server: rtServer, releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot'
        rtMaven.deployer server: rtServer, releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local'
        buildInfo = rtMaven.run pom: './pom.xml', goals: 'clean install'
      }
    }
    stage('build helloworld-service docker') {
      dir ('examples-java/helloworld-service') {
        tagDockerApp = dockerReg+'/'+dockerNamespace+'/'+"helloworld-service"+':'+dockerFinalTag
        docker.build(tagDockerApp)
        rtDocker.push(tagDockerApp, 'docker-stage-local', buildInfo)
      }
    }
    stage('build guestbook-service docker') {
      dir ('examples-java/guestbook-service') {
        tagDockerApp = dockerReg+'/'+dockerNamespace+'/'+"guestbook-service"+':'+dockerFinalTag
        docker.build(tagDockerApp)
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: CREDENTIALS, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
              rtDocker = Artifactory.docker("${env.USERNAME}", "${env.PASSWORD}")
              rtDocker.push(tagDockerApp, 'docker-stage-local', buildInfo)
        }        
      }
    }
    stage('build helloworld-ui docker') {
      dir ('examples-java/helloworld-ui') {
        tagDockerApp = dockerReg+'/'+dockerNamespace+'/'+"helloworld-ui"+':'+dockerFinalTag
        docker.build(tagDockerApp)
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: CREDENTIALS, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
              rtDocker = Artifactory.docker("${env.USERNAME}", "${env.PASSWORD}")
              rtDocker.push(tagDockerApp, 'docker-stage-local', buildInfo)
        }        
      }
    }
    stage('push BuildInfo') {
      rtServer.publishBuildInfo buildInfo
    }	   
}
